#!/usr/bin/env python3
"""Strict shared projection for the portable Prodcraft routing digest."""

from __future__ import annotations

import hashlib
import re


PORTABLE_ROUTING_SECTIONS = (
    "Skill Selection Priority",
    "Workflow Selection",
    "Fast-Track Rules",
)
SKILL_TOKEN_RE = re.compile(
    r"(?<![a-z0-9\-/])`?(?P<name>pc-[a-z0-9]+(?:-[a-z0-9]+)*)`?(?![a-z0-9\-/])"
)
REPO_ONLY_LIFECYCLE_PATH_RE = re.compile(
    r"(?<![a-z0-9_-])(?:[0-9]{2}-[a-z0-9-]+|cross-cutting)/"
    r"pc-[a-z0-9]+(?:-[a-z0-9]+)*(?![a-z0-9_/-])"
)


def extract_portable_routing_sections(gateway_text: str) -> list[tuple[str, str]]:
    sections: list[tuple[str, str]] = []
    for heading in PORTABLE_ROUTING_SECTIONS:
        match = re.search(rf"^## {re.escape(heading)}\s*$", gateway_text, re.MULTILINE)
        if match is None:
            raise ValueError(f"gateway is missing required routing section `{heading}`")
        remainder = gateway_text[match.end() :]
        next_heading = re.search(r"^##\s+", remainder, re.MULTILINE)
        body = remainder[: next_heading.start()] if next_heading else remainder
        body = body.strip()
        if not body:
            raise ValueError(f"gateway required routing section `{heading}` is empty")
        sections.append((heading, body))
    return sections


def render_portable_routing_map(
    gateway_text: str,
    *,
    public_skill_names: set[str],
    manifest_skill_names: set[str],
    planned_skill_names: set[str],
) -> str:
    """Render selected gateway routing sections for curated-only consumers.

    Implemented public skills become navigable sibling-package links. Skills
    that exist only in the source repository and planned skills remain visible
    but carry explicit availability markers instead of dangling links.
    """

    sections = extract_portable_routing_sections(gateway_text)
    projection = "\n\n".join(f"## {heading}\n\n{body}" for heading, body in sections)
    repo_only_paths = sorted(set(REPO_ONLY_LIFECYCLE_PATH_RE.findall(projection)))
    if repo_only_paths:
        raise ValueError(
            f"portable routing sections contain repo-only lifecycle path {repo_only_paths}"
        )
    referenced_names = {match.group("name") for match in SKILL_TOKEN_RE.finditer(projection)}
    known_names = manifest_skill_names | planned_skill_names | {"pc-prodcraft"}
    unknown_names = sorted(referenced_names - known_names)
    if unknown_names:
        raise ValueError(f"portable routing sections reference unknown skills {unknown_names}")

    def replace_skill(match: re.Match[str]) -> str:
        name = match.group("name")
        if name in public_skill_names:
            return f"[{name}](../../{name}/SKILL.md)"
        if name in planned_skill_names:
            return f"`{name}`[^planned]"
        return f"`{name}`[^not-included]"

    rendered_projection = SKILL_TOKEN_RE.sub(replace_skill, projection)
    source_digest = hashlib.sha256(projection.encode("utf-8")).hexdigest()
    return (
        "# Portable Routing Map\n\n"
        "> Generated from the canonical `skills/_gateway.md`; do not edit this file by hand.\n\n"
        f"> Source projection: `sha256:{source_digest}`\n\n"
        "This digest carries the routing tables that a curated-only installation can use safely. "
        "When a route names an unavailable skill, stop at [pc-intake](../../pc-intake/SKILL.md) and request the canonical "
        "repository or install that package; do not silently claim that the unavailable gate ran.\n\n"
        f"{rendered_projection}\n\n"
        "[^not-included]: This implemented skill is not included in this curated surface. Use an installed source-repository copy, or stop at [pc-intake](../../pc-intake/SKILL.md) and report partial-entry guidance.\n"
        "[^planned]: This skill is planned and is not implemented or included in this curated surface. Do not route to it as an available capability.\n"
    )
